src/Entity/TvShow.php
<?php

namespace App\Entity;

use App\Repository\TvShowRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TvShowRepository::class)
 */
class TvShow
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"tvshows", "characters"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=80)
     * @Assert\NotBlank(message="Merci de saisir un titre pour la série")
     * @Groups({"tvshows", "characters"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Groups({"tvshows", "characters"})
     * @Assert\NotBlank(message="Merci de saisir un synopsis pour la série")
     */
    private $synopsis;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Groups({"tvshows", "characters"})
     */
    private $image;

     /**
     * @ORM\Column(type="string", length=80, nullable=true)
     * @Groups({"tvshows", "characters"})
     */
    private $imageurl;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"tvshows", "characters"})
     */
    private $nbLikes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="tvShow", orphanRemoval=true)
     * @ORM\OrderBy({"seasonNumber"="DESC"})
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Character::class, inversedBy="tvShows")
     */
    private $characters;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="tvShows")
     * @ORM\OrderBy({"name"="DESC"})
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
    */
    private $Poster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->publishedAt = new DateTime();
        $this->createdAt = new DateTime();
        $this->updatedAt = new DateTime();
        $this->characters = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getNbLikes(): ?int
    {
        return $this->nbLikes;
    }

    public function setNbLikes(?int $nbLikes): self
    {
        $this->nbLikes = $nbLikes;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setTvShow($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getTvShow() === $this) {
                $season->setTvShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Character[]
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): self
    {
        if (!$this->characters->contains($character)) {
            $this->characters[] = $character;
        }

        return $this;
    }

    public function removeCharacter(Character $character): self
    {
        $this->characters->removeElement($character);

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getImageurl(): ?string
    {
        return $this->imageurl;
    }

    public function setImageurl(?string $imageurl): self
    {
        $this->imageurl = $imageurl;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->Poster;
    }

    public function setPoster(?string $Poster): self
    {
        $this->Poster = $Poster;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/TvShowType.php
<?php

namespace App\Form;

use App\Entity\TvShow;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class TvShowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre de la série',
                'required' => true,

            ])
            ->add('synopsis', null, [
                'label' => 'Synopsis'
            ])
            ->add('image', FileType::class, [
                'label' => 'Image pour illustrer',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Veuillez ajouter une image valide',
                    ])
                ],
            ])
            ->add('nbLikes', null, [
                'label' => 'Nombre de likes'
            ])
            ->add('publishedAt', null, [
                'label' => 'Date de publication'
            ])
            ->add('createdAt', null, [
                'label' => 'Date de création'
            ])
            ->add('updatedAt', null, [
                'label' => 'Date de mise à jour'
            ])
            ->add('characters', null, [
                'label' => 'Les personnages',
                'required' => true,
            ])
            ->add('categories', null, [
                'label' => 'Les catégories',
                'required' => true,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Valider',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TvShow::class,
        ]);
    }
}

src/Controller/Admin/TvShowController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Character;
use App\Entity\Season;
use App\Entity\TvShow;
use App\Form\SeasonType;
use App\Form\TvShowType;
use App\Form\Type\CharacterType;
use App\Repository\TvShowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/admin/tvshow", name="admin_tvshow_", requirements={"index" = "\d+"})
 */
class TvShowController extends AbstractController
{
    /**
     * 
     * URL : /admin/tvshow/list , nom de la route : admin_tvshow_list
     * 
     * @Route("/list", name="list")
     */
    public function index(TvShowRepository $tvShowRepository): Response
    {
        return $this->render('admin/tvshow/index.html.twig', [
            'tvshows' => $tvShowRepository->findAll(),
        ]);
    }

    /**
     * 
     * @Route("/add", name="add")
     * 
     * @return void
     */
    public function add(Request $request, SluggerInterface $slugger)
    {
        $tvShow = new TvShow();

        $form = $this->createForm(TvShowType::class, $tvShow);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd($tvShow);

            $imageFile = $form->get('image')->getData();

            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
               
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }

                $tvShow->setImageurl($newFilename);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($tvShow);
            $em->flush();

            // Message flash
            $this->addFlash('success', 'La série ' . $tvShow->getTitle() . ' a bien été ajoutée');

            return $this->redirectToRoute('tvshow_list');
        }

        return $this->render('admin/tvshow/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     *
     * @Route("/{id}", name="show")
     * @return void
     */
    public function show(int $id, TvShowRepository $tvShowRepository)
    {
        $tvshow = $tvShowRepository->find($id);  

        // dd($tvshow);

        return $this->render('admin/tvshow/show.html.twig', [
            'tvshow' => $tvshow
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit")
     */
    public function edit(TvShow $tvShow, Request $request)
    {
        $form = $this->createForm(TvShowType::class, $tvShow);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            $this->addFlash('success', 'La série ' . $tvShow->getTitle() . ' a bien été mise à jour');

            return $this->redirectToRoute('admin_tvshow_show', ['id' => $tvShow->getId()]);
        }

        return $this->render('admin/tvshow/edit.html.twig', [
            'form' => $form->createView(),
            'tvShow' => $tvShow
        ]);
    }

    /**
     *
     * @Route("/{id}", name="update")
     * @return Response
     */
    public function update(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $tvshow = $entityManager->getRepository(TvShow::class)->find($id);

        // dd($tvshow);

        if (!$tvshow) {
            throw $this->createNotFoundException(
                'No tvshow found for id '.$id
            );
        }

        $tvshow->setTitle('New tvshow title!');
        $entityManager->flush();

        return $this->redirectToRoute('admin_tvshow_show', [
            'id' => $tvshow->getId()
        ]);
    }

    /**
     *
     * @Route("/{id}", name="delete")
     * @return Response
     */
    public function delete(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $tvshow = $entityManager->getRepository(TvShow::class)->find($id);

        // dd($tvshow);

        if (!$tvshow) {
            throw $this->createNotFoundException(
                'No tvshow found for id '.$id
            );
        }

        $entityManager->remove($tvshow);
        $entityManager->flush();

        return $this->redirectToRoute('admin_tvshow_list', [
            'id' => $tvshow->getId()
        ]);
    }

    /**
     * @Route("/{id}/season/add", name="season_add")
     * 
     * URL : /admin/tvshow/{id}/season/add
     * 
     * {id} ==> L'identifiant de la série
     * 
     * PSR-12
     *
     * @return void
     */
    public function addNewSeason(TvShow $tvShow, Request $request)
    {
        $season = new Season();

        $form = $this->createForm(SeasonType::class, $season);

        // On récupère les données du formulaire que l'on inhjectera
        // dans l'objet $season
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On associe la saison $season à notre série
            $tvShow->addSeason($season);

            $em = $this->getDoctrine()->getManager();

            // La saison n'existe pas encore en BDD, on la fait
            // donc persister (on la rajoute à la liste d'entités que Doctrine devra gérer)
            $em->persist($season);

            // On sauvegarde les données en BDD
            // - On crée la saison
            // - On met à jour la série (on lui associe la nouvelle saison)
            $em->flush();

            // Message de success
            $this->addFlash('success', "La saison numéro {$season->getSeasonNumber()} a bien été associée à la série {$tvShow->getTitle()}");

            // On redirige vers la vue détaillée d'une série
            return $this->redirectToRoute('admin_tvshow_show', ['id' => $tvShow->getId()]);
        }

        return $this->render('admin/tvshow/season_add.html.twig', [
            'form' => $form->createView(),
            'tvShow' => $tvShow
        ]);
    }

    /**
     * @Route("/{id}/character/add", name="character_add")
     * 
     * URL : /admin/tvshow/{id}/character/add
     * 
     * {id} ==> L'identifiant de la série
     * 
     * PSR-12
     *
     * @return void
     */
    public function addNewCharacter(TvShow $tvShow, Request $request)
    {
        $character = new Character();

        $form = $this->createForm(CharacterType::class, $character);

        // On récupère les données du formulaire que l'on injectera
        // dans l'objet $character
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On associe le personnage $character à notre série
            $tvShow->addCharacter($character);

            $em = $this->getDoctrine()->getManager();

            // La saison n'existe pas encore en BDD, on la fait
            // donc persister (on la rajoute à la liste d'entités que Doctrine devra gérer)
            $em->persist($character);

            // On sauvegarde les données en BDD
            // - On crée la saison
            // - On met à jour la série (on lui associe la nouvelle saison)
            $em->flush();

            // Message de success
            $this->addFlash('success', "Le personnage {$character->getFirstname()} a bien été associée à la série {$tvShow->getTitle()}");

            // On redirige vers la vue détaillée d'une série
            return $this->redirectToRoute('admin_tvshow_show', ['id' => $tvShow->getId()]);
        }

        return $this->render('admin/tvshow/character_add.html.twig', [
            'form' => $form->createView(),
            'tvShow' => $tvShow
        ]);
    }
}

templates/tvshow/add.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{{form(form)}}{% endblock %}

templates/tvshow/details.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{tvShow.title}} -
    {{ parent() }}
{% endblock %}

{% block body %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                {% for category in tvShow.categories %}
                    <a href="#"><span class="badge bg-secondary">{{ category.name }}</span></a>            
                {% endfor %}
                <h1 class="fw-light">{{tvShow.title}}</h1>
                <img src="{{ asset('images/' ~ tvShow.imageurl) }}" alt="" height="400">
                <p class="lead text-muted">
                {% for season in tvShow.seasons %}
                    <a href=""><span class="badge bg-secondary">Saison {{ season.seasonNumber }}</span></a>
                        {% for episode in season.episodes %}
                            <p>{{ episode.title }}</p>    
                        {% endfor %}
                    {% endfor %}
                </p>
                <p class="lead text-muted">
                {% for char in tvShow.characters %}
                    Personnages : {{ char.firstname }}
                {% endfor %}
                </p>
            </div>
        </div>
    </section>

<section>
   
</section>

 <div class="py-5 bg-light">
    <div class="container">
        <p>
            {{tvShow.synopsis}}
        </p>
    </div>
</div>

<div class="py-5 bg-light">
    <div class="container">
        <a href="{{ path('tvshow_list') }}">Retour à la liste</a>
    </div>
</div>

{% endblock %}

templates/tvshow/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Séries | 
	{{ parent() }}
{% endblock %}

{% block body %}
	{% include "partials/_search.html.twig" %}
{% endblock %}

templates/tvshow/list.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ parent() }}
{% endblock %}

{% block body %}

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Dernières séries</h1>
            </div>
        </div>
    </section>

    <div class="py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for tvshow in tvshows %}
                    <div class="col">
                        <div class="card shadow-sm">
                            {% set imagetvshow = tvshow.poster %}
                            {% if tvshow.image %}
                                {% set imagetvshow = asset('uploads/images/' ~ tvshow.image) %}
                            {% endif %}
                            <img src="{{imagetvshow ?? 'https://via.placeholder.com/200'}}" class="card-img-top" alt="Affiche de la série {{tvshow.title}}" width="200">
                            <div class="card-body">
                                <p class="card-text">
                                    {{tvshow.title}}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ path('tvshow_slug', {slug:tvshow.slug}) }}" class="btn btn-sm btn-outline-secondary">Voir</a>
                                        {% if is_granted('ROLE_ADMIN') %}
                                            <a href="{{ path('admin_tvshow_edit', {id:tvshow.id}) }}" class="btn btn-sm btn-outline-secondary">Editer</a>
                                        {% endif %}
                                    </div>
                                    <small class="text-muted">
                                        {{tvshow.nbLikes}}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewbox="0 0 16 16">
                                            <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                                        </svg>
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

</main>

{% endblock %}